### PR TITLE
Fix extra events in FST traces (#5405).

### PR DESCRIPTION
**Pull request by wsnyder**
Attempted fix to #5405.

@kbieganski I make the patch below, which appears to fix the issue, but it core dumps occasionally as the event pointer is bad.  I'm confused as this code works ok for vcd - maybe we just got lucky?  Is this doing something fundamentally wrong?

### CODE REVIEW

**Comment by wsnyder** [comment]
Note it seems to only core dump on multithreaded runs.

```
        #vltmt/t_timing_trace_fst: %Error: Exec of obj_vltmt/t_timing_trace_fst/Vt_timing_trace_fst failed: %Warning: vltmt/t_timing_trace_fst: Exec failed with core dump
        #vltmt/t_trace_event_fst: %Error: Exec of obj_vltmt/t_trace_event_fst/Vt_trace_event_fst failed: %Warning: vltmt/t_trace_event_fst: Exec failed with core dump

```

**Comment by kbieganski** [comment]
The pointer is bad because the offload buffer never actually stores the pointer. It didn't crash before because the pointer wasn't used for anything.

This patch fixes the segfault:

```diff
diff --git i/include/verilated_trace.h w/include/verilated_trace.h
index dd47ad81b..8de17f123 100644
--- i/include/verilated_trace.h
+++ w/include/verilated_trace.h
@@ -608,7 +608,8 @@ public:
     void chgEvent(uint32_t code, const VlEventBase* newval) {
         m_offloadBufferWritep[0] = VerilatedTraceOffloadCommand::CHG_EVENT;
         m_offloadBufferWritep[1] = code;
-        m_offloadBufferWritep += 2;
+        *reinterpret_cast<const VlEventBase**>(m_offloadBufferWritep + 2) = newval;
+        m_offloadBufferWritep += 4;
         VL_DEBUG_IF(assert(m_offloadBufferWritep <= m_offloadBufferEndp););
     }
 };
diff --git i/include/verilated_trace_imp.h w/include/verilated_trace_imp.h
index 94549dc19..d22abe9db 100644
--- i/include/verilated_trace_imp.h
+++ w/include/verilated_trace_imp.h
@@ -169,7 +169,8 @@ void VerilatedTrace<VL_SUB_T, VL_BUF_T>::offloadWorkerThreadMain() {
                 continue;
             case VerilatedTraceOffloadCommand::CHG_EVENT:
                 VL_TRACE_OFFLOAD_DEBUG("Command CHG_EVENT " << top);
-                traceBufp->chgEvent(oldp, reinterpret_cast<const VlEventBase*>(readp));
+                traceBufp->chgEvent(oldp, *reinterpret_cast<const VlEventBase* const*>(readp));
+                readp += 2;
                 continue;

                 //===
```

**Comment by wsnyder** [comment]
@kbieganski thanks!  Note VCD had the same code, so that probably explains why I thought it worked for VCD but @katsui97 did not.

I still see the test as not stable with this change.  Perhaps the pointer is not guaranteed to persist?  I'm thinking I'll instead try calling isTriggered before doing the push of the event to the trace queue - if you see problems with that let me know.

**Comment by wsnyder** [comment]
I realized in vltmt case the pointer that tracing sees can be to the old state of the model, as the simulation has moved on.

**Comment by wsnyder** [comment]
Updated to now check before enquing, but the --vltmt doesn't match the single threaded --vlt run, so more changes needed.

**Comment by wsnyder** [comment]
Will be merging manually.

**Pull request closed without merging**
