### PR TITLE
Remove C-style cast in VPI_HANDLE

### PR DESCRIPTION
**Pull request by toddstrader**
Makes the Codacy check happy.  Also admits that we're ditching `const` here (thanks VPI).

### CODE REVIEW

**Review by wsnyder — COMMENTED** [review]
Why char and not keep PLI_BYTE8?

**Comment by toddstrader** [comment]
> Why char and not keep PLI_BYTE8?

Not really sure.  But yeah, no reason to change it.

**Review by wsnyder — COMMENTED** [review]
Sorry, didn't notice earlier, should it be nullptr?

**Comment by toddstrader** [comment]
> Sorry, didn't notice earlier, should it be nullptr?

Yeah, Codacy wasn't yelling about that but agreed that is the more type safe option.

**Pull request merged**
