### PR TITLE
Add a workflow that calls clang-format and commit.

### PR DESCRIPTION
**Pull request by yTakatsukasa**
I'm wondering it would be convenient if clang-format automatically runs and update the code.

This draft PR is to experiment.

Of course just checking rather than changing the code is also doable.

I will push some meaningless commit to see if clang-format works as expected.

### CODE REVIEW

**Comment by yTakatsukasa** [comment]
aef08e11be858fc20e0fc23035685b6ca42241fa is my _noise_ commit.

1a6c1bd42c44ed4f746a7aa8ba588c78612cc5d2 looks executed on my repository [here](https://github.com/yTakatsukasa/verilator/runs/1570321461?check_suite_focus=true).

**Comment by wsnyder** [comment]
Like it; once working and happy feel free to merge.

**Comment by yTakatsukasa** [comment]
This workflow works on my repository as 1a6c1bd42c44ed4f746a7aa8ba588c78612cc5d2 and [here](https://github.com/yTakatsukasa/verilator/runs/1570321461?check_suite_focus=true).
New flows in a PR don't get executed at the destination repository of the PR (here in this case).
It is probably security reason. (Someone may let do bad things by sending PR including malicious workflow)

I pushed 67fddd401f7d1d26fbaf9beaf9305881bcddf2f6 to run other CIs just in case.
I will merge after CI passes.

**Comment by yTakatsukasa** [comment]
The workflow properly works at master :tada:
https://github.com/verilator/verilator/runs/1570947337?check_suite_focus=true

**Pull request merged**
