### PR TITLE
Add class specific same methods for AstVarScope, AstVar, and AstScope (#4203)

### PR DESCRIPTION
**Pull request by jlwehle**
Addresses issue-4203

### CODE REVIEW

**Comment by wsnyder** [comment]
Do you have a test (related to #4203 presumably) you can add to this patch to show why it's needed and so we can avoid breaking it in the future?

**Comment by jlwehle** [comment]
The test case is in issue-4203 ... which is known to fail on FreeBSD, however I would expect it to fail on Ubuntu if llvm libcxx (and friends) was being used (I believe llvm clang targets the GNU libraries by default on Ubuntu).  On FreeBSD 12 it fails using the stock compiler / libraries (both llvm 13.0 based) and using a llvm 15.0.7 compiler / libraries toolchain I built.

Basically this may require expanding the CI matrix to avoid future breakage.

**Comment by jlwehle** [comment]
A complete approach which doesn't require expanding the CI matrix would be a C++ test case which for each node type creates a typical node, clones it, systematically modifies the various fields of that copy, and verifies that for each case where the copy produces a different hash, that the equal_to operator also says the node is not equal to the original.

I'm not sure how to best implement that for the existing testing harness.

**Comment by wsnyder** [comment]
Please update your github name per the contrib test failure, and force-push the changes again, then should be good to go.

**Comment by jlwehle** [comment]
I confess to not having much git experience ... I updated my name and ran "git push --force".  Did I need any additional options to "force-push the changes again"?

**Pull request merged**
