### PR TITLE
Added support for function call with and without parenthesis

### PR DESCRIPTION
**Pull request by svenka3**
See #3902.

### CODE REVIEW

**Review by wsnyder — COMMENTED** [review]
Looks ok, but @RRozak  needs to review.

Note if you need to make changes just "git push --force", no need to make a new pull request.

**Comment by svenka3** [comment]
I got one issue with this proposed fix, without my fix the following test fails with nice error:

```log
%Error: t/t_class_member_bad3.v:16:12: Static access to non-static member variable 'member'
```

After my proposed fix, this error is not showing up, rather it appears later from g++ as below:

```log
Vt_class_member_bad3___024root__DepSet_h40331809__0__Slow.cpp:19:50: error: invalid use of non-static data member ‘Vt_class_member_bad3___024unit__03a__03aFoo::member’
   19 |     Vt_class_member_bad3___024unit__03a__03aFoo::member = 1U;
      |                                                  ^~~~~~
```

So it needs closer look. @wsnyder @RRozak please help.

**Comment by wsnyder** [comment]
I think that was related to a change I made earlier today.  Please pull then 'git merge master -m merge' into your branch and 'git push --force'

**Comment by svenka3** [comment]
> I think that was related to a change I made earlier today. Please pull then 'git merge master -m merge' into your branch and 'git push --force'

Thanks, I did that prior to this PR (I went through a few iterations - originally forked it from chipalliancec/verilator, so had to remove/fork again from verilator/verilator - while doing so I did get all latest. So when I now do git merge, I get:

```log
 git merge master -m master
Already up to date.
```
Any clues? My PR blocked on that failure.

**Comment by wsnyder** [comment]
Applying your patch to master I get passes.  Maybe you pulled into "origin" but then didn't update your personal "master"? 

Anyhow we have what we need to apply it, I just need @RRozak to comment.

**Comment by svenka3** [comment]
Closing this as I wrongly deleted a negative/bad test. Opened a new PR thanks to the hints from @RRozak and @wsnyder

**Pull request closed without merging**
