### PR TITLE
V3Timing: use 64bit for delay type

### PR DESCRIPTION
**Pull request by xdch47**
Fix attempt the issue of #3973 - not sure about side effects and also architecture wise.
I could also introduce `dtypeSetSigned64()` .

Other possible point to fix the problems might be:

https://github.com/verilator/verilator/blob/master/src/V3Number.cpp#L2338
https://github.com/verilator/verilator/blob/master/src/V3Timing.cpp#L512

### CODE REVIEW

**Review by wsnyder — COMMENTED** [review]
Thanks for debugging, your attempt makes sense.

IEEE says $rtoi returns an integer so I think the old code was correct for implementing rtoi. Instead to fix the time issue I think whatever makes the AstRToI needs to either make a new ast type AstRToQ (quad).  AstRToQ would look just like AstRToI but you need to make the change you made here.

**Comment by xdch47** [comment]
https://github.com/verilator/verilator/blob/master/src/V3Timing.cpp#L514 there?

**Comment by wsnyder** [comment]
Looks right.

**Comment by xdch47** [comment]
Hi, just looking again into this and noticed that it looks like `$rtoi` uses ASTRToIS
and the place where i tried to fixed it is `ASTRToIRoundS` which is not standart relevant right?

And further the comment for `AstRToIRoundS` looks misleading:
https://github.com/verilator/verilator/blob/0395fb2065f00d241e420afe2e5f78a5324ef492/src/V3AstNodeExpr.h#L4873

And another thing is that https://github.com/verilator/verilator/blob/master/src/V3Number.cpp#L2338 seem like an implementation for converting to Integer without any size limitations (upto 2**1023).

so could you please once more look into it, if the fix attempt was really wrong and its neccessary to introduce `ASTRToQ`?
AstRToIRoundS ins only used in https://github.com/verilator/verilator/blob/master/src/V3Timing.cpp#L512 and
https://github.com/verilator/verilator/blob/master/src/V3Width.cpp#L1957, https://github.com/verilator/verilator/blob/master/src/V3Width.cpp#L6645, https://github.com/verilator/verilator/blob/master/src/V3Width.cpp#L378 (just visit)

Maybe the default size should  32bits and update by https://github.com/verilator/verilator/blob/master/src/V3Number.cpp#L2338 ?

**Comment by wsnyder** [comment]
You're right, please update the comment you mentioned to say it's used internally only for timing, implicit conversion and is 64 bits.  Then update the contributor agreement test to pass (maybe update your name in github - see the error), then should be good to merge.

**Comment by xdch47** [comment]
After a close look to the source resizing via `valuep->dtypeSetBitSized` looks like an adequate fix for me.

**Pull request merged**
