### PR TITLE
Init params in constructor to support pre-c++11 compilers

### PR DESCRIPTION
**Pull request by elgorwi**
Fix consts from #2370 as raised in issue #2424 .
Remove const cast for vars.

### CODE REVIEW

**Comment by wsnyder** [comment]
Seems basically sound, could you please get Travis passing?

**Comment by elgorwi** [comment]
> Seems basically sound, could you please get Travis passing?

Apologies for the delay. 
Looking at the Travis logs, I don't understand the failure. Is there a way to see build artifact ```obj_vlt/t_vpi_param/Vt_vpi_param__Slow.cpp``` from Travis?
If not, what would be the best approach to reproduce the error locally? I'm running on OSX.
Thanks

**Comment by gezalore** [comment]
I think what it is trying to say is that var_t__DOT__PARAM_STR is declared after __Vm_mt_final in the class, while in the constructor initializer list var_t__DOT__PARAM_STR is before __Vm_mt_final (member initializers should be in declaration order): 

```
class A {
 int a;
 int b;
 A() : b(0), a(0) {}  // incorrect
 A (): a(0), b(0) {}  // correct
}
```

**Comment by gezalore** [comment]
"test_regress/t/t_vpi_param --vltmt" might reproduce. Possibly after hacking max_procs in driver.pl to return 2 (the number of CPUs on a Travis worker).

**Comment by elgorwi** [comment]
OK I see, this is related to multi threading. 
Thanks for the suggestions @gezalore .

**Comment by gezalore** [comment]
Yes, in multithreaded mode the fields are ordered in a different way. I think this is the relevant code:
https://github.com/verilator/verilator/blob/23e4a0f7845334a24a6c083fa52771163905cc00/src/V3EmitC.cpp#L2802-L2850

**Comment by elgorwi** [comment]
Travis is now passing. @wsnyder can you review?

**Comment by gezalore** [comment]
I run `make clang-format` and pushed to master to get the cron regressions working. Thank you for the fix.

**Pull request closed without merging**
