### PR TITLE
[bug #3140] fix internal error caused by nodep->declElWidth() == 0

### PR DESCRIPTION
**Pull request by filamoon**
We appreciate your contributing to Verilator.  If this is your first commit, please add your name to docs/CONTRIBUTORS, and read our contributing guidelines in docs/CONTRIBUTING.rst.

### CODE REVIEW

**Comment by filamoon** [comment]
Can't pass the contributor agreement check. No idea...

**Comment by wsnyder** [comment]
Think In docs/CONTRIBUTORS you added Zh*e*nglei Wang,

but your name in github is Zh*a*nglei Wang

**Comment by filamoon** [comment]
So this is a negative test, which will generate a warning and fail the regression. What to do?

**Comment by wsnyder** [comment]
>So this is a negative test, which will generate a warning and fail the regression. What to do?

I'm not understanding.

Does your name have an "a" or "e"?  Based on that either change your github name or docs/CONTRIBUTORS.

**Comment by filamoon** [comment]
I meant, besides the contributor agreement check, there are other test failures. Since the test I added is a negative test, it will generate a warning (so the test itself will fail).

**Comment by wsnyder** [comment]
Oh, rename the test t_bigmen_bad, then for the .pl file use an example like t_gen_cond_bitrange_bad.pl
this will also make an example output file which you need to create.  Create and update it the first time by running

test_regress/t/t_bigmen_bad.pl --gold

then git add t_gen_cond_bitrange_bad.out

**Pull request merged**
