### PR TITLE
V3Common.cpp::makeVlToString: fix `VL_TOSTRING_W` statement generation (#4188)

### PR DESCRIPTION
**Pull request by apstrike**
add the inclusion of the missing width argument

This is a fix for #4188 

We appreciate your contributing to Verilator.  If this is your first commit, please add your name to docs/CONTRIBUTORS, and read our contributing guidelines in docs/CONTRIBUTING.rst.

### CODE REVIEW

**Comment by wsnyder** [comment]
Thanks for the fix.  Could you add a test that shows the issue (and gets fixed) please?

**Comment by apstrike** [comment]
to be honest, I don't know the verilator internal code well enough to understand what exactly triggers a call to `makeVlToString` with a "wide" object & I can't share the code that originally triggered this. If you have some insight on what's going on here then I probably could whip something up.

**Comment by wsnyder** [comment]
I suspect a struct bit member variable of e.g. >= 65 bits will hit this once you call $display on the object.

**Comment by apstrike** [comment]
yes, looks like enable `--trace-structs` does the trick. I'll push out a new commit with the test hopefully soon.

**Comment by apstrike** [comment]
@wsnyder I've added in a regression test that reproduces the problem pre fix (and passes post fix!)

**Pull request merged**
