### PR TITLE
Link performance critical libraries statically

### PR DESCRIPTION
**Pull request by gezalore**
I hope this is not too controversial, but with this the overall compilation speeds are now exactly 60% faster (with -O3) compared to my starting point before any optimization.

### CODE REVIEW

**Comment by wsnyder** [comment]
Seems reasonable, this only increases the binary size by a few MB which is well worth the performance gain.

I was curious why you preferred --disable-static over --enable-dynamic, but looks like other libraries allow e.g. --enable-dynamic --enable-static, so guess it makes sense?

When I first read this I thought you were changing the Verilated model to static.  Now I see you didn't which is fine as the performance stuff should not be using clib. If that is ever considered some notes I thought of: 1. we'd need a cmake rule to match, and 2. think it would be better to figure out the static libraries needed always and have a makeflag to determine if they are used or not (post Verilation.

BTW I see ~+10% using clang++ over GCC with same flags, mileage varies but you might want to try that if have not.

I'll run this patch a few more places and probably will apply tomorrow.

**Comment by gezalore** [comment]
As I mentioned I only saw 800KB increase in the binary size (the optimised one, not the debug version) so I would be interested to know what platform have you seen the few MBs on.

I went with --disable-static as this is new behaviour that I think is beneficial enough for the common case that it should be on by default, but if anybody has special requirements (or experiences issues, which I don’t expect, but you never know) then it can be turned off. Also I think normally --enable-static for building libraries means produce a *.a rather than/as well as a *.so, but what we do here is quite different in that we only partially static link a final executable (which is still a dynamically linked exe in the end), so I thought the disable variant is more likely to prod the user to read the help text. If you would like, I would be happy to rename it --disable-partial-staic. I’m not great at naming things.

I have noticed that configure.ac is a bit murky around what flags and tests are for building the model and what flags and tests are for building Verilator itself. It might worth clarifying that at some convenient point but currently I think it’s fine as it is. For your reference, all I ever intended to changed so far relate only to Verilator and not the model. BTW is there a reason I am not aware of for using the custom _MY_* macros for testing the platform rather than the built in AC_* autoconf ones?

**Comment by wsnyder** [comment]
If the AC_* can do what is needed it's fine to use them.  The _MY's have some differences, e.g. allow setting a specific variable, but I might have missed some AC_ feature that's equivelent.

I agree they should be documented better, I committed a cleanup to indicate what each flag affects. In your patch please edit the doc string to say "... Use this to link Verilator binary dynamically."  Also fix spelling of statically.

**Comment by gezalore** [comment]
Ah, I see the confusion caused by the “link everything dynamically” bit.  Note the Verilator binary is always dynamically linked against non performance critical libraries like libc and pthread. The flag makes it dynamically link against the performance critical libraries as well (as it did before the patch). I will update the patch tomorrow (I’m on UTC+0).

**Comment by gezalore** [comment]
I have updated the help text. I also went with the longer --disable-partial-static option to avoid ambiguity with the common --enable-static option.

**Pull request closed without merging**
