### PR TITLE
Peter GitHub/master

### PR DESCRIPTION
**Pull request by PeterMonsson**
This is a partial fix for issue #1292. The implication operator |-> is converted into the expression !(a || b) in AST. Is this too much of an AST hack? The other operator |=> would probably not work correctly with disable iff for example.

### CODE REVIEW

**Comment by wsnyder** [comment]
Peter, you need in your ~/.github
 
       name = Peter Monsson

**Comment by wsnyder** [comment]
Converting it is fine.  Other minor stuff - please remove the carriage returns from the added files, and add to Changes in the three star section:

        *** Support implication "->|" operator.

Then I think this is good to go.

BTW VerilogPerl which parses these has a more complicated way to handle the expressions which is needed when we get to fancier stuff, but we can clean up that when needed

**Comment by wsnyder** [comment]
Peter, you need in your ~/.gitconfig (mistyped above)

   name = Peter Monsson

**Comment by PeterMonsson** [comment]
I had my .gitconfig set correctly locally, but I didn't have the correct name in my profile settings. Hopefully this is sorted now? Line endings are sorted too.

**Comment by wsnyder** [comment]
Don't worry about the last test failure, I'll download, clean, review and if good push.

**Comment by wsnyder** [comment]
FIxed spacing and pushed. Thanks for the contribution.

**Pull request closed without merging**
