### PR TITLE
Use make variable CFG_GCH_IF_CLANG instead of .gch extension

### LINKED ISSUE #5698: Hard-coded PCH filenames with .gch instead of $(CFG_GCH_IF_CLANG)
For some reason my platform is not appending the .gch extension which is causing compilation errors.

### PR DESCRIPTION
**Pull request by awmoore-intel**
Fixes #5698

### CODE REVIEW

**Comment by wsnyder** [comment]
This doesn't make sense.  Are you certain that running:

          clang++ a.cpp -o a.fast.gch

does not create `a.fast.gch`?  I'd be very shocked if the compiler is disobeying the `-o`.

if this works, there's something else going wrong in the file.

if this does not, I think we really want to keep a unique suffix; perhaps we use _fast.gch instead if it somehow doesn't like the double dot.

**Comment by wsnyder** [comment]
Note if you did not ./configure with the same clang++, or used gcc instead of clang++ this may explain the problem.

**Comment by awmoore-intel** [comment]
> Note if you did not ./configure with the same clang++, or used gcc instead of clang++ this may explain the problem.

Ahh. yes, I used gcc and cmake.

**Comment by wsnyder** [comment]
Ok, no fix needed then.

**Pull request closed without merging**
