### PR TITLE
Don't warn for index width mismatch if index is known good constant

### PR DESCRIPTION
**Pull request by gezalore**
This removes 2/3 of the width warnings causing the fracas in #2433 

Basically it disables the width mismatch warning in bit selects if the index is constant and is a known in-range value. otherwise you get the SELRANGE waring if constant or a WIDTH warning if non-constant.

@wallento, @wsnyder I would think this is an OK relaxation of the width checks. If you agree I will polish/add tests/etc or let me know how to go about it.

### CODE REVIEW

**Comment by wallento** [comment]
Maybe this could similarly to the suggestion in #2441 be two different levels: WIDTH and WIDTH-EXACT

**Comment by wallento** [comment]
"WIDTH-EXACT" (or maybe even more fine granular) would probably get into lint-style

**Comment by wsnyder** [comment]
As to WIDTH-EXACT we should discuss in the other bug, but as disabling WIDTH is common I think that should be the verbose one.

I think I am probably ok with this but I need some tests so I can see what falls out.

**Comment by wsnyder** [comment]
Think this has been abandoned for now.

**Pull request closed without merging**
