### PR TITLE
Fix passing arguments by reference (#3385 partial)

### PR DESCRIPTION
**Pull request by RRozak**
It fixes passing function arguments by reference. Currently on master, they are handled as output arguments. This way, the argument passed by reference has always the default value at the beginning of the function.
In this PR, reference arguments are handled as `inout` arguments. It is correct in most of the cases. I think the only case in which these kinds of arguments shouldn't be handled in the same way is a case with forks.
Another difference is that `inout` arguments accept more types of expressions. Currently on master, only varrefs are supported in both `ref` and `inout` arguments. I added a support for all types that are allowed to be passed to `ref` argument, but only in non-inlined function. In a case with inlined functions var scopes are used, so probably a bigger change is required.

### CODE REVIEW

**Comment by wsnyder** [comment]
I think we need ref - adding notes to #3385.

**Comment by RRozak** [comment]
I think the approach is correct. I described it in #3385. I also applied required changes after your fix of inout arguments.
Now a few tests fail. They do due to the constant propagation. Sometimes a variable reference that is passed to a `ref` argument is replaced by a constant. I will disable this optimization in such cases.

**Comment by RRozak** [comment]
I think it isn't needed. I took a look on generated files and the code looks correct. In inlined cases formal arguments are replaced with actual arguments. In functions that aren't inlined the actual arguments remain in calls. No copies are made in any of these cases. The tests that I added pass. `t_queue_persistence.pl` (inlined case) still doesn't work, due to the type of the argument. It may be easy to add support for other types of arguments, but I didn't work on it.

**Comment by RRozak** [comment]
I fixed the problem with constant propagation by marking variable references passed to `ref` arguments as `READWRITE`.

**Comment by RRozak** [comment]
Fails are caused by the problem with randc.
Do you think it can be merged now?

**Pull request merged**
