### PR TITLE
Avoid using <tab> in the middle of lines

### PR DESCRIPTION
**Pull request by ldoolitt**
Doing so invites confusion and different views by different editors.
Three special-cases left, where any alternative is worse.

### CODE REVIEW

**Comment by wsnyder** [comment]
install-sh comes with configure so should probably not be changed.

Perhaps you could also mprove t_dist_tabs.pl to error on these so more do not creep in?

**Comment by ldoolitt** [comment]
> install-sh comes with configure so should probably not be changed.

I checked before changing this file, and we already have local patches to it. See issue #1203 and commit c28a6ee from 2017. If you'd rather, I could recreate the patch without this.

> Perhaps you could also mprove t_dist_tabs.pl to error on these so more do not creep in?

Maybe. The Makefile-comment thing is definitely a special case.  I also had to purposefully not look at gtkwave or test_regress files. I have told myself for years that I should try to get some cleanups like this into the upstream gtkwave tree.

**Comment by wsnyder** [comment]
ok I'll take install-sh. I'll merge and consider a separate pull to test please.

**Comment by ldoolitt** [comment]
`t_dist_tabs.pl` already warns in general when new tabs appear.  The only possible improvement would be to check more currently-exempt files for non-tab followed by tab.  Well, except for \#-tab at the beginning of a line in something Makefile-related.
I can do it, but it will be messy.

Contrasting your exempt file list with mine, I found one other source file with ugly tab usage: `test_regress/t/t_preproc.v`.
Also, `nodist/fastcov.py` no longer needs to be exempt.

**Pull request merged**
