### PR TITLE
Travis: store the .ccache directory

### PR DESCRIPTION
**Pull request by gezalore**
To test ccache persistence hypothesis

### CODE REVIEW

**Comment by gezalore** [comment]
@wsnyder this is how long a fully ccached build should take:
https://travis-ci.com/github/verilator/verilator/builds/169119262

Currently the only thing stored in the cache is the verilator build tree in $HOME/verilator_cache. The ccache is not stored because:
1. $HOME/.ccache is not persisted
2. Multiple jobs in the test stage use the same cache because of: https://docs.travis-ci.com/user/caching/#caches-and-build-matrices which means they would thrash each others stored caches anyway.

Point 2 is illustrated by:
https://travis-ci.com/github/verilator/verilator/builds/169111095
vs
https://travis-ci.com/github/verilator/verilator/builds/169114118
Observe only one of the test stage jobs gets a speed gain from persiting $HOME/.ccache

BTW I don't think there is anything special about "Travis's ccache", it simply supposed to add ccache to the path and add $HOME/.ccache to the persisted directories.

Also note this PR is not the right fix as now the build stage is useless as verilator is rebuilt later all the time

If the intention was to persist the ccache, I can look into this further, but we still need to keep all builds below 50 minutes to avoid the timeout even if the cache is wiped.

**Comment by wsnyder** [comment]
The intention was to persist the ccache of the build, so that the tests could pickup the build.  I certainly didn't do any detailed analysis as you have done as to if we were/should/could cache tests.

Presumably due to these findings we should be saving the cache only on the builds?  Then tests have the cache only local to that run (either by not saving the cache or using a different cache for the test phase)?

**Comment by toddstrader** [comment]
$HOME/.cccache did persist at one point.  Perhaps when $VERILATOR_CACHE was specified as a cache directory, that broke this.  Also, I'm sure there is a limit to the size of the cache, but I can't seem to find that documented anywhere.  I believe we were close to the top of that, but of course now can't say for sure because I can't find the number.  In any case, something else to watch out for.

**Comment by gezalore** [comment]
> The intention was to persist the ccache of the build, so that the tests could pickup the build.

The tests can pick up the build but not because of the ccache is persisted, but because the build tre itself is persisted. 

The immediate point I was trying to demonstrate is that I think even without the cache persistence, the FreeBSD builds  (#2390/#2393) should be fast enough to runt he tests with just a local ccache installation as the longest test job is about 20 minutes + 12 minutes to build Verailator.

Long term, I think we can get the best of both worlds using: https://docs.travis-ci.com/user/using-workspaces I will look into this.

**Pull request closed without merging**
