### PR TITLE
Fix the error "use of undeclared identifier 'WIFEXITED'" by adding #include <sys/wait.h>

### PR DESCRIPTION
**Pull request by yurivict**
We appreciate your contributing to Verilator.  If this is your first commit, please add your name to docs/CONTRIBUTORS, and read our contributing guidelines in docs/CONTRIBUTING.adoc.

### CODE REVIEW

**Comment by wsnyder** [comment]
I suspect this header isn't in windows, so needs to be included under sys/time.h in the ifdef.

Also please add your github name to docs/CONTRIBUTORS - you'll get a test failure soon otherwise.

**Comment by yurivict** [comment]
I've updated the pull request.

**Comment by wsnyder** [comment]
Thanks. Pushed this manually to avoid the dist test issue.

**Comment by poucotm** [comment]
Hi, I think the patch is needed also for windows (Mingw). The same errors occur when compiling for windows. I added codes below with reference to [sys/wait.h](https://api.kde.org/kdesupport-api/apidox-kdesupport/kdewin-apidocs/mingw_2sys_2wait_8h_source.html)

V3Os.cpp :
```
// clang-format off
#if defined(_WIN32) || defined(__MINGW32__)
# include <windows.h>   // LONG for bcrypt.h on MINGW
# include <bcrypt.h>  // BCryptGenRandom
# include <chrono>
# include <direct.h>  // mkdir
# include <psapi.h>   // GetProcessMemoryInfo
# include <thread>
# ifndef WIFEXITED
#  define WIFEXITED(w)    (((w) & 0xff) == 0)
#  define WIFSIGNALED(w)  (((w) & 0x7f) > 0 && (((w) & 0x7f) < 0x7f))
#  define WIFSTOPPED(w)   (((w) & 0xff) == 0x7f)
#  define WEXITSTATUS(w)  (((w) >> 8) & 0xff)
#  define WTERMSIG(w) ((w) & 0x7f)
#  define WSTOPSIG    WEXITSTATUS
# endif
#else
# include <sys/time.h>
# include <sys/wait.h> // Needed on FreeBSD for WIFEXITED
# include <unistd.h>  // usleep
#endif
// clang-format on
```

**Comment by wsnyder** [comment]
@poucotm are you saying an additional include of sys/wait.h is needed?  If so could you please consider making a pull request with it?

**Pull request closed without merging**
