### PR TITLE
Docker upgrade to Ubuntu 20.04

### PR DESCRIPTION
**Pull request by wallento**
Draft for the upgrade to Ubuntu 20.04. ~~Still need to silence the linter.~~

### CODE REVIEW

**Comment by wallento** [comment]
Ah, it seems that the linter is deactivated, did you do that already? Great!

**Comment by wsnyder** [comment]
I believe systemc is now available via apt so we should use that versus building.

With that, and it passing, push at will.

**Comment by wallento** [comment]
Ah, right, read about that. Nice, will do.

**Comment by wallento** [comment]
What do you think about trying to get in other Compilers via a PPA (if available)? Currently its GCC 9 only.

**Comment by wsnyder** [comment]
I'd suggest we install clang in addition to cpp and leave it at that for now.

**Comment by wsnyder** [comment]
@wallento Good to go if add clang?  (Still marked draft). Thanks

**Comment by wallento** [comment]
Hi, sorry, I got stalled when it didn't build with clang (visit override). Will look into it now!

**Comment by wallento** [comment]
Has been fixed meanwhile, will soon push.

**Comment by wallento** [comment]
Pushed and waiting, ready to be merged

**Pull request merged**
