### PR TITLE
Remove empty math node visitor as it is required to evaluate part sel…

### PR DESCRIPTION
**Pull request by margej**
…ects

We appreciate your contributing to Verilator.  If this is your first commit, please add your name to docs/CONTRIBUTORS, and read our contributing guidelines in docs/CONTRIBUTING.rst.

### CODE REVIEW

**Comment by margej** [comment]
Test case added to PR

**Comment by wsnyder** [comment]
Thanks. Feel free to squash push on tests passing.

**Comment by margej** [comment]
Being plagued by inability to test due to #2920

**Comment by margej** [comment]
test_regress/t/t_sv_cpu.pl is failing
combo process assigning via a function call in a modport of a parameterised interface!

Trying to reduce testcase since this particular test is a full and relatively complex multi-file design

**Comment by margej** [comment]
Simplified testcase:
```
interface genbus_if( );

logic [15:0] m_mdata[1];
logic  [1:0] m_re   [1];

modport master( import mConnect, output m_mdata, output m_re );

function automatic void mConnect( input  logic id,
                                  input  logic [15:0] mdata,
                                  input  logic [1:0] re  );
begin
    m_mdata[id] = mdata;
    m_re   [id] = re; // Latch
end
endfunction

endinterface

// ---------------------------------------------

module cpu( genbus_if.master dbus);

always_comb dbus.mConnect( 0, 16'h1234, 2'd3 );

endmodule

// ---------------------------------------------

module t();

  genbus_if dbus();

  cpu i_cpu ( .dbus (dbus.master) );

endmodule
```

Latch detected because bounds checking of id in mConnect inserts an else-less if (I guess constant propagation is disabled in this instance, or has not be done yet (V3Active))

```
    1:2:2:2:2:2: ASSIGN 0x1ef6b60 <e815> {c23bc} @dt=0x1efc830@(G/w1)
    1:2:2:2:2:2:1: CONST 0x1ef6590 <e791> {c23bc} @dt=0x1efc830@(G/w1)  1'h0
    1:2:2:2:2:2:2: VARREF 0x1ef6a60 <e792> {c8bw} @dt=0x1efc830@(G/w1)  __Vtask_mConnect__0__id [LV] => VARSCOPE 0x1ef6130 <e787> {c8bw} @dt=0x1efc830@(G/w1)  TOP->__Vtask_mConnect__0__id -> VAR 0x1ef6010 <e784> {c8bw} @dt=0x1efc830@(G/w1)  __Vtask_mConnect__0__id BLOCKTEMP

<snip>

    1:2:2:2:2:2: IF 0x1ef9d00 <e572> {c13am}
    1:2:2:2:2:2:1: GTE 0x1ef3180 <e571> {c13am} @dt=0x1efff20@(G/nw1)
    1:2:2:2:2:2:1:1: CONST 0x1ef4460 <e550> {c13am} @dt=0x1efc830@(G/w1)  1'h0
    1:2:2:2:2:2:1:2: VARREF 0x1ef4570 <e551> {c13an} @dt=0x1efc830@(G/w1)  __Vtask_mConnect__0__id [RV] <- VARSCOPE 0x1ef6130 <e787> {c8bw} @dt=0x1efc830@(G/w1)  TOP->__Vtask_mConnect__0__id -> VAR 0x1ef6010 <e784> {c8bw} @dt=0x1efc830@(G/w1)  __Vtask_mConnect__0__id BLOCKTEMP
    1:2:2:2:2:2:2: ASSIGN 0x1efc290 <e569> {c13am} @dt=0x1f007a0@(G/w2)
    1:2:2:2:2:2:2:1: VARREF 0x1efc350 <e567> {c13am} @dt=0x1f007a0@(G/w2)  __Vlvbound2 [RV] <- VARSCOPE 0x1ef5cc0 <e691> {c13am} @dt=0x1f007a0@(G/w2)  TOP.__PVT__t__DOT__dbus->__Vlvbound2 -> VAR 0x1f01f40 <e559> {c13am} @dt=0x1f007a0@(G/w2)  __Vlvbound2 MODULETEMP
    1:2:2:2:2:2:2:2: ARRAYSEL 0x1efc450 <e568> {c13am} @dt=0x1f007a0@(G/w2)
    1:2:2:2:2:2:2:2:1: VARREF 0x1ef58a0 <e450> {c13af} @dt=0x1ef75c0@(w2)u[0:0]  m_re [LV] => VARSCOPE 0x1efb070 <e676> {c4ao} @dt=0x1ef75c0@(w2)u[0:0]  TOP.__PVT__t__DOT__dbus->m_re -> VAR 0x1efc580 <e400> {c4ao} @dt=0x1ef75c0@(w2)u[0:0]  m_re [LATCHED] [VSTATIC]  VAR
    1:2:2:2:2:2:2:2:2: VARREF 0x1ef59a0 <e451> {c13an} @dt=0x1efc830@(G/w1)  __Vtask_mConnect__0__id [RV] <- VARSCOPE 0x1ef6130 <e787> {c8bw} @dt=0x1efc830@(G/w1)  TOP->__Vtask_mConnect__0__id -> VAR 0x1ef6010 <e784> {c8bw} @dt=0x1efc830@(G/w1)  __Vtask_mConnect__0__id BLOCKTEMP
 /* 1:2:2:2:2:2:3: No else triggers latch detection */
```
@wsnyder, Is there a simple way I can evaluate that this 'if' in fact has a constant conditional at compile time (as we can see in the .tree snippet above it boils down to comparison between 2 constants), or perhaps latch detection should be moved to a later pass where this if may have been eliminated?

**Comment by wsnyder** [comment]
That constant because it goes via a variable won't get recognized until much later (V3Gate) which is too late for V3Latch to work right.  Maybe we could specially mark the If to say ignore for latch purposes (a bit hacky, but...)?

**Comment by margej** [comment]
Ok thanks. Not looked into it yet, but any tips on how to reliably recognize a bounds checking 'if' node would be appreciated.

**Comment by margej** [comment]
This looks good to merge now

**Pull request merged**
