### PR TITLE
Fix to escape `VERILATOR_ROOT`

### LINKED ISSUE #3764: `VERILATOR_ROOT` was not properly escaped
Thanks for taking the time to report this.

Can you attach an example that shows the issue?  (Must be openly licensed, ideally in test_regress format.)

1. I use the following command to generate the `VMyTopLevel.mk` and other files

```bash
 set -e ; verilator_bin.exe -CFLAGS -fPIC -CFLAGS -m64 -CFLAGS -shared -CFLAGS -Wno-attributes -LDFLAGS -fPIC -LDFLAGS -m64 -LDFLAGS -shared -LDFLAGS -Wno-attributes -CFLAGS -I"jniIncludes" -CFLAGS -I"jniIncludes/win32" -CFLAGS -fvisibility=hidden -LDFLAGS -fvisibility=hidden -CFLAGS -std=c++11 -LDFLAGS -std=c++11 --autoflush   --output-split 5000 --output-split-cfuncs 500 --output-split-ctrace 500 -Wno-WIDTH -Wno-UNOPTFLAT -Wno-CMPCONST -Wno-UNSIGNED --x-assign unique --x-initial-edge --trace-depth 0 -O3 -CFLAGS -O0 -CFLAGS -DTRACE --trace  --Mdir verilator --top-module MyTopLevel  -cc "C:/Users/Administrator/IdeaProjects/SpinalHDL/tmp/job_1/MyTopLevel.v" --exe verilator/VMyTopLevel__spinalWrapper.cpp 
```

2. Then I try to make it with `make -f VMyTopLevel.mk`, it throws an error

```
Can't open perl script "C:msys64clang64shareverilator/bin/verilator_includer": No such file or directory
```

3. I found that the path was not properly escaped in file `VMyTopLevel.mk`

```Makefile
VERILATOR_ROOT = C:\msys64\clang64\share\verilator
```

What 'verilator --version' are you using?  Did you try it with the git master version?

What OS and distribution are you using?

Windows 11 with SpinalHDL 1.7.3

May we assist you in trying to fix this in Verilator yourself?

I found that the path was correctly deslashed in file `V3EmitCMake.cpp`.

https://github.com/verilator/verilator/blob/0322e9da7ed52bca9b8fa5d8d7170f3fea7f8c56/src/V3EmitCMake.cpp#L75-L81

https://github.com/verilator/verilator/blob/0322e9da7ed52bca9b8fa5d8d7170f3fea7f8c56/src/V3EmitCMake.cpp#L100-L101

But it was not deslashed in file `V3EmitMk.cpp`.

https://github.com/verilator/verilator/blob/0322e9da7ed52bca9b8fa5d8d7170f3fea7f8c56/src/V3EmitMk.cpp#L158-L159

### PR DESCRIPTION
**Pull request by kazutoiris**
We appreciate your contributing to Verilator.  If this is your first commit, please add your name to docs/CONTRIBUTORS, and read our contributing guidelines in docs/CONTRIBUTING.rst.

fix #3764

### CODE REVIEW

**Comment by kazutoiris** [comment]
🤔 Maybe it would be better to modify the `V3Options::getenvXXXX` directly.

**Review by wsnyder — COMMENTED** [review]
I'm not sure that blindly replacing \ with / was even correct in the CMakefile, as in theory there could be backslashes in filenames that are relevant, but this is probably rare enough we can ignore it.

Please move deslash to V3String so it can be common, then you can also remove it from the CMake.

There's a couple of deslash's missing e.g. for the SYSTEMC_ defines.

**Comment by kazutoiris** [comment]
1. Change the `V3Options::getenvXXXX` maybe more convenient. I add `VString::escapeStringForPath` in `V3String.cpp`, it will escape the `\` and `space`.
2. In the `V3EmitCMake.cpp`, there's no need to deslash the file path, because it has been correctly escaped.
  By the way, `VString::quoteAny` **must behind** the `deslash`, imagine that `Hello "World"`
  * When `VString::quoteAny` behind the `deslash`, `Hello "World"` -> `Hello "World"` -> `Hello \"World\"`
  * But now, `VString::quoteAny` before the `deslash`, `Hello "World"` -> `Hello \"World\"` -> `Hello /"World/"`, that's totally wrong.
https://github.com/verilator/verilator/blob/5634e96bb6151b7a1d7f70e57ab81186d74d3793/src/V3EmitCMake.cpp#L46
So, I removed all `deslash` in `V3EmitCMake.cpp`
3. Just escape the `verilator_bin.exe` path is enough, because other dependencies' paths are escaped correctly.

**Comment by kazutoiris** [comment]
Need to update the `t_tri_array.out`, that's not my fault. 😢 

https://github.com/verilator/verilator/blob/5634e96bb6151b7a1d7f70e57ab81186d74d3793/test_regress/t/t_tri_array.out#L18

**Pull request merged**
