### PR TITLE
Fix msvc

### PR DESCRIPTION
**Pull request by codelec**
Signed-off-by: Kritik Bhimani <bhimanikritik@gmail.com>

We appreciate your contributing to Verilator.  If this is your first commit, please add your name to docs/CONTRIBUTORS, and read our contributing guidelines in docs/CONTRIBUTING.rst.

### CODE REVIEW

**Review by wsnyder — COMMENTED** [review]
Thanks for separating.  Maybe you're not done yet. Just noting I still would appreciate this having the _MSC_VER number checked, and VL_UNREACHABLE implemented as described in #3811 comments.

**Comment by codelec** [comment]
checking for _MSC_VER value may not help since MS follows a different nomenclature than open source ones (there was no need to explicitly mention in cmake about c++ std in use). so as long as _MSC_VER is defined that should indicate which compiler is doing the work

**Comment by wsnyder** [comment]
Did you try what is in the reference I posted?  https://stackoverflow.com/questions/5047971/how-do-i-check-for-c11-support

     #if __cplusplus >= 201103L || (defined(_MSC_VER) && _MSC_VER >= 1900)

**Comment by wsnyder** [comment]
Looks good, as discussed in #3813 we might end up changing the version number we check for in _MSC_VER, but we might as well take these improvements now.

**Pull request merged**
