### PR TITLE
Update to clang-format-11

### PR DESCRIPTION
**Pull request by gezalore**
With clang-format 11, nested ternaries come out legible. It is available on 20.04 via `apt install clang-format-11`.

Any objection to updating?

### CODE REVIEW

**Comment by wsnyder** [comment]
Fundamentally upgrading seems fine.

I don't like all the extra spaces that are inserted within a line in the ? :'s, as seems an easy way to miss something and looks unlike any other indenting currently.  Is there a setting to disable that?

After merging this we should make another commit to use IndentPPDirectives PPDIS_AfterHash, and many of the clang format off/on pragmas can be deleted as they will then indent correctly.  I'll do this if you don't want to.

**Comment by gezalore** [comment]
do you mean you dont like the extra spaces between the condition and the `?`/final `:`  like here?
```
        const uint32_t tabMod = dtypep->subDTypep()->isString() ? 1  // String
                                : elemBytes <= 2   /*HERE*/     ? 8  // CData, SData
                                : elemBytes <= 4                ? 4  // IData
                                : elemBytes <= 8                ? 2  // QData
                                                                : 1;
```

Ther is no way to disable that afaik. The only thing that influences a ternary apart from `AlignOperands` is `BreakBeforeTernaryOperators`. You get the spaces in either case, and seems like they are baked into version 11+.

**Comment by wsnyder** [comment]
Ok, my preference isn't a reason to give up on the new version.

**Comment by gezalore** [comment]
OK, if you wouldn't mind doing the IndentPPDirectives thing please, I think you know better what you mean there.

**Comment by wsnyder** [comment]
The problem with IndentPPDirectives is it doesn't allow single space indent per level which we and many other projects use, so will change this with some future version.

**Comment by gezalore** [comment]
FWIW looks like 13 will have PPIndentWidth

**Pull request merged**
