### PR TITLE
Enabling latest C++ Standard Compilation flag

### PR DESCRIPTION
**Pull request by AmeyaVS**
* Enables C++17/20(2a) Compiler flags
* For SystemC Project sets the CXX_STANDARD flag from SystemC CMake build config.

    - Handles linking issues with SystemC: #1339, and #2147 using CMake build.

**Note:** 
* For Makefile projects using SystemC one needs to pass the same CXXSTD compilation flag manually.
* Or, Configure Verilator with appropriate C++ Standard flags matching the SystemC build C++ standard flag.

### CODE REVIEW

**Comment by wsnyder** [comment]
Thanks for making a contribution!

I wonder if we should be adding the 2x given it's experimental?  Traditionally we've only added the versions after ISO approval (e.g. gcc20, c++20 but not gcc2x/c++2x).

**Comment by AmeyaVS** [comment]
I can update those `c++2a` flags to `c++20` and keep them as _**comments**_ for now.
Once the compilers supports the standard we can enable the flags then.
Let me know your thoughts on that.

As for the `CMakeLists.txt` changes, it would enable one to have a consistent C++ standard compiler flags for Verilator SystemC projects.

**Comment by wsnyder** [comment]
Yes, thanks I think using "20" commented is better.  The other changes all make sense.

**Comment by AmeyaVS** [comment]
I saw the build failures. It is to `SystemC` repository package being used in regression system.
Should I remove the `C++=17` flags from the configure scripts?
It would require one to build `SystemC` library from scratch/source to match the settings in Verilator.

**Comment by wsnyder** [comment]
I suspect that's why 17 was commented out.

I don't understand your build-from-scratch comment given the regressions use ubuntu 20.04's prebuilt SystemC.

**Comment by AmeyaVS** [comment]
For the comment:

      It would require one to build SystemC library from scratch/source to match the settings in Verilator.

I meant downloading the `SystemC` source and building a customized version with `C++17` enabled.
For my use case I usually build `SystemC` library locally on my system, enabling customized flags.
I rarely use the ones from package manager for such work.

**Comment by wsnyder** [comment]
Makes sense.

**Comment by AmeyaVS** [comment]
Updated/reverted the `configure.ac` to C++14 as packaged SystemC library seems to be built with default C++14 flag.

Currently submitting a suggestion in Debian/Ubuntu repo maintainers for a patch which can help in this regard.

**Comment by AmeyaVS** [comment]
I have posted the query on the Ubuntu launchpad forum for removing the C++ Standard Dependency for SystemC library.
But I am yet to get back from them.

For now, one can look at the following commit [here](https://github.com/AmeyaVS/systemc/commit/0b32d4a1061d882bb79085fdfff0365000f85fd1) for more details on removing the C++ Standard Dependency for the clients of SystemC library.

**Pull request merged**
