### PR TITLE
Fix missing flex include path variable (#4970)

### PR DESCRIPTION
**Pull request by ct-clmsn**
This PR contains a fix for #4970

### CODE REVIEW

**Comment by wsnyder** [comment]
Thanks for contributing, can you please fix your github name, and avoid the copyright change, so the tests pass. Thanks.

**Comment by ct-clmsn** [comment]
@wsnyder where do I fix my name? Would this be my GitHub name in the display on the site?

**Comment by wsnyder** [comment]
>@wsnyder where do I fix my name? Would this be my GitHub name in the display on the site?

Yes, correct, thanks.

Please also merge or rebase-in the verilator master as we fixed some regression issues.

**Comment by wsnyder** [comment]
Your patch still shows all changes made on master (look here on git hub), can you please remake your pull with just your changes and "git push --force"?

**Comment by wsnyder** [comment]
@ct-clmsn ping on re-pushing, so we can merge and close this out, thanks.

**Comment by wsnyder** [comment]
@ct-clmsn ping on re-pushing, so we can merge and close this out, thanks.

**Comment by wsnyder** [comment]
Merged manually.

**Pull request closed without merging**
