### PR TITLE
#3370 : Include VK_USER_OBJS dependency in libCreate mode

### PR DESCRIPTION
**Pull request by margej**
We appreciate your contributing to Verilator.  If this is your first commit, please add your name to docs/CONTRIBUTORS, and read our contributing guidelines in docs/CONTRIBUTING.rst.

### CODE REVIEW

**Comment by wsnyder** [comment]
Please recreate the patch off from master, as there's a bunch of other confusing stuff in it, which doesn't seem to merge if I just take the single V3EmitMk.cpp change.  Also please add to Changes:

```
 * Fix Bison 3.8.2 error (#3366). [elike-ypq]
 * Fix rare bug in -Oz (V3Localize) (#3286). [Geza Lore, Shunyao CAD]
 * Fix filenames with dots overwriting debug .vpp files (#3373).
+* Fix including VK_USER_OBJS in make library (#3370) (#3376). [Julien Margetts]
```

(or likewise a good description).  Then should be good to go, thanks.

**Comment by wsnyder** [comment]
Please recreate the patch off from master, as there's a bunch of other confusing stuff in it, which doesn't seem to merge if I just take the single V3EmitMk.cpp change.  Also please add to Changes:

```
 * Fix Bison 3.8.2 error (#3366). [elike-ypq]
 * Fix rare bug in -Oz (V3Localize) (#3286). [Geza Lore, Shunyao CAD]
 * Fix filenames with dots overwriting debug .vpp files (#3373).
+* Fix including VK_USER_OBJS in make library (#3370) (#3376). [Julien Margetts]
```

(or likewise a good description).  Then should be good to go, thanks.

**Comment by margej** [comment]
Looks like master on my fork has a bunch of unwanted commits. I'll bin this PR and try again ...

**Comment by wsnyder** [comment]
Minor note for next time, you can "--force" push a new pull request's commits into an existing pull request, to save you filing a new ticket.

**Pull request closed without merging**
