### PR TITLE
Optimize fine grained trace activity flags

### PR DESCRIPTION
**Pull request by gezalore**
Hi @wsnyder, I am quite happy with this, I just wanted to check if you have some memory about why we only used a byte array for the fine grained activity flags when using mtasks (I understand the atomicity aspect). Please see the 'firstly' bit in the commit message. The bitvector is indeed more compact but it seems to have no effect on tracing performance on SweRV EH1, if anything it makes things a little slower.

BTW, since 1d0a726437c84e30c5810c6bd2f60df7a486c10a I am getting perl erros from:
https://github.com/verilator/verilator/blob/1d0a726437c84e30c5810c6bd2f60df7a486c10a/test_regress/driver.pl#L391
about `$process->{running_id}` being undefined.

### CODE REVIEW

**Comment by wsnyder** [comment]
On a much larger design with many more tasks using a bitvector was somewhat slower.  Swerv doesn't have a lot of parallelism so it probably won't show up.  I suppose we could have a bitvector per mtask then combine them, but that will still require extra instructions to bit pack & merge so I suspect won't be worth the performance nor extra code to maintain.

**Comment by gezalore** [comment]
Hmm, I wonder how far in scale that design was, Swerve still has almost 800 flags, afer this optimization it is still 600.

**Comment by wsnyder** [comment]
I don't have access to it now to check, sorry.

**Comment by gezalore** [comment]
No worries, I will see if I can find something bigger just to be safe.

**Comment by wsnyder** [comment]
Note SweRV-EH2 core is now openly available, it is slightly bigger.

**Comment by gezalore** [comment]
Ah, I didn't notice that, thanks!

Actually, I tried it on a private design, but I ran into a bug introduced by this:
https://github.com/verilator/verilator/commit/a41ea180fa4dec1cc57a02a0ab2f8645164d7882

which causes this assertion to fail:
https://github.com/verilator/verilator/blob/9c0c6439ccbe8b46d064e5368a18f8ba87312770/src/V3Expand.cpp#L326

I am investigating, but if you have some nugget of wisdom please let me know..

**Comment by wsnyder** [comment]
No nuggets, thanks for looking into it.

**Comment by gezalore** [comment]
So I tried this on a privete larger design, where it also buys 8+% tracing speed, on SweRV EH1 and EH2 it helps by about 2%, as those seem to have fewer opportunities for the introduced optimization to remove conditionals.

**Pull request merged**
